openapi: 3.2.0
info:
  title: SMS Gateway REST APIv2 Documentation API
  version: 1.0.0
  description: The Optus SMS Suite Mobile Gateway REST APIv2 allows you to send SMS messages to a single handset.
servers:
- url: https://api.sms.optus.com.au/rest/sms/v2
security:
- GatewayAuthorizer: []
tags:
- name: Documentation
paths:
  /openapi.yaml:
    summary: API documentation
    get:
      tags:
      - Documentation
      description: API documentation
      security: []
      responses:
        '200':
          description: OK
        '404':
          description: Not found
      summary: Get openapi yaml
      x-summary-source: derived
      operationId: getOpenapiYaml
      x-operation-id-source: derived
components:
  securitySchemes:
    GatewayAuthorizer:
      description: HTTP Basic Authentication is used for all authenticated requests.
      type: apiKey
      name: Authorization
      in: header
